-- Acentua o texto que ja estava gravado na conta de demonstracao.
--
-- A correcao nao passa pela API de proposito: PUT /api/v1/animais/{id} grava um
-- evento "Cadastro atualizado" na linha do tempo, e as vinte e oito fichas
-- ganhariam um evento que nao aconteceu. Cada UPDATE casa o texto antigo inteiro
-- e so alcanca o abrigo da demonstracao; rodar duas vezes nao muda mais nada.
--
-- Uso: psql guarida -v ON_ERROR_STOP=1 -f acentos-da-demo.sql
BEGIN;
UPDATE animal SET historia = 'Apareceu no portão do abrigo numa noite de chuva, magro e com medo de barulho. Hoje dorme de barriga para cima e late para carteiro por esporte.' WHERE historia = 'Apareceu no portao do abrigo numa noite de chuva, magro e com medo de barulho. Hoje dorme de barriga para cima e late para carteiro por esporte.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Resgatada de dentro do motor de um carro no estacionamento de um mercado. Levou duas semanas para sair de baixo do sofá, e agora escolhe colo.' WHERE historia = 'Resgatada de dentro do motor de um carro no estacionamento de um mercado. Levou duas semanas para sair de baixo do sofa, e agora escolhe colo.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Ficou dois anos preso numa corrente curta antes de ser resgatado. Precisa de quintal e de gente com paciência, e devolve isso em lealdade.' WHERE historia = 'Ficou dois anos preso numa corrente curta antes de ser resgatado. Precisa de quintal e de gente com paciencia, e devolve isso em lealdade.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Nasceu no abrigo, filha da Estrela. Nunca conheceu rua, e por isso é a mais confiada da ninhada.' WHERE historia = 'Nasceu no abrigo, filha da Estrela. Nunca conheceu rua, e por isso e a mais confiada da ninhada.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Vive no abrigo desde filhote e já viu três ninhadas crescerem. É o gato que recebe os novos e mostra onde fica a comida.' WHERE historia = 'Vive no abrigo desde filhote e ja viu tres ninhadas crescerem. E o gato que recebe os novos e mostra onde fica a comida.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Entregue por uma família que comprou na feira sem saber que coelho vive oito anos. Come alface na mão de quem senta no chão.' WHERE historia = 'Entregue por uma familia que comprou na feira sem saber que coelho vive oito anos. Come alface na mao de quem senta no chao.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Resgatado de uma gaiola pequena demais, com as penas da asa cortadas. Já voa de novo e assobia o refrão de uma música que ninguém identificou ainda.' WHERE historia = 'Resgatado de uma gaiola pequena demais, com as penas da asa cortadas. Ja voa de novo e assobia o refrao de uma musica que ninguem identificou ainda.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Encontrada na rodovia, com a pata quebrada. A pata soldou torta e ela corre igual, só que de lado.' WHERE historia = 'Encontrada na rodovia, com a pata quebrada. A pata soldou torta e ela corre igual, so que de lado.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Caiu do telhado de um vizinho e ninguém apareceu para buscar. Sobe em tudo, e por isso o abrigo pede tela nas janelas.' WHERE historia = 'Cai do telhado de um vizinho e ninguem apareceu para buscar. Sobe em tudo, e por isso o abrigo pede tela nas janelas.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Idosa, chegou quando a tutora faleceu e ninguém da família quis ficar. Dorme dezoito horas por dia e acorda para comer.' WHERE historia = 'Idosa, chegou quando a tutora faleceu e ninguem da familia quis ficar. Dorme dezoito horas por dia e acorda para comer.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Devolvido duas vezes por causa da fama da raça, nunca por comportamento. É o cachorro mais paciente da casa com criança.' WHERE historia = 'Devolvido duas vezes por causa da fama da raca, nunca por comportamento. E o cachorro mais paciente da casa com crianca.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET raca = 'Siamês misturado' WHERE raca = 'Siames misturado' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Da ninhada encontrada atras da padaria. A única que miava alto o bastante para ser achada.' WHERE historia = 'Da ninhada encontrada atras da padaria. A unica que miava alto o bastante para ser achada.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Chegou com medo de homem de boné. Levou um ano para aceitar a mão do voluntário que hoje é o preferido dele.' WHERE historia = 'Chegou com medo de homem de bone. Levou um ano para aceitar a mao do voluntario que hoje e o preferido dele.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Resgatada de uma casa com quinze cães em dois cômodos. Passou a acreditar que comida não vai acabar.' WHERE historia = 'Resgatada de uma casa com quinze caes em dois comodos. Passou a acreditar que comida nao vai acabar.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Entrou pela janela do abrigo por conta própria e nunca mais saiu. Ninguém reclamou dele em lugar nenhum.' WHERE historia = 'Entrou pela janela do abrigo por conta propria e nunca mais saiu. Ninguem reclamou dele em lugar nenhum.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Semiferal, resgatada de um terreno baldio. Aceita comida e cafuné curto, e mais que isso ainda está negociando.' WHERE historia = 'Semiferal, resgatada de um terreno baldio. Aceita comida e cafune curto, e mais que isso ainda esta negociando.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Cão de guarda de um depósito que fechou. Ficou sozinho no terreno duas semanas antes de alguém avisar.' WHERE historia = 'Cao de guarda de um deposito que fechou. Ficou sozinho no terreno duas semanas antes de alguem avisar.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Devolvida depois da Páscoa, como acontece todo ano. Come cenoura pela ponta e deixa o resto.' WHERE historia = 'Devolvida depois da Pascoa, como acontece todo ano. Come cenoura pela ponta e deixa o resto.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Filhote grande que ainda não sabe o tamanho que tem. Derruba tudo por empolgação e pede desculpa depois.' WHERE historia = 'Filhote grande que ainda nao sabe o tamanho que tem. Derruba tudo por empolgacao e pede desculpa depois.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Gata preta, o que no Brasil ainda faz gente hesitar. Fica no abrigo há mais tempo que gatos de cores comuns que chegaram depois.' WHERE historia = 'Gata preta, o que no Brasil ainda faz gente hesitar. Fica no abrigo ha mais tempo que gatos de cores comuns que chegaram depois.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Atropelado e abandonado na porta da clínica veterinária. Anda com uma manqueira leve que não incomoda.' WHERE historia = 'Atropelado e abandonado na porta da clinica veterinaria. Anda com uma manqueira leve que nao incomoda.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET raca = 'SRD' WHERE raca = 'Malhada' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Cresceu junto com uma ninhada de cachorro e acha que é cachorro. Busca bolinha.' WHERE historia = 'Cresceu junto com uma ninhada de cachorro e acha que e cachorro. Busca bolinha.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Precisa de escovação toda semana, o que foi o motivo de ter sido entregue. Fica manso quando escovado.' WHERE historia = 'Precisa de escovacao toda semana, o que foi o motivo de ter sido entregue. Fica manso quando escovado.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET nome = 'Pérola' WHERE nome = 'Perola' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Energia de sobra, precisa de caminhada longa todo dia. Não serve para apartamento e o abrigo avisa antes.' WHERE historia = 'Energia de sobra, precisa de caminhada longa todo dia. Nao serve para apartamento e o abrigo avisa antes.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Vivia num pet shop que fechou. Passou a vida inteira em vitrine e ainda estranha espaço aberto.' WHERE historia = 'Vivia num pet shop que fechou. Passou a vida inteira em vitrine e ainda estranha espaco aberto.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE animal SET historia = 'Chegou junto com a Cacau, do mesmo resgate. Os dois se dão bem e o abrigo prefere que sejam adotados juntos.' WHERE historia = 'Chegou junto com a Cacau, do mesmo resgate. Os dois se dao bem e o abrigo prefere que sejam adotados juntos.' AND abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE candidatura SET cidade = 'Niterói' WHERE cidade = 'Niteroi' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET mensagem = 'Moro sozinha, trabalho de casa três dias por semana e tenho tela em todas as janelas.' WHERE mensagem = 'Moro sozinha, trabalho de casa tres dias por semana e tenho tela em todas as janelas.' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET nome = 'João Lima' WHERE nome = 'Joao Lima' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET cidade = 'São Gonçalo' WHERE cidade = 'Sao Goncalo' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET mensagem = 'Tenho quintal murado e já tenho uma cadela de sete anos, castrada e sociável.' WHERE mensagem = 'Tenho quintal murado e ja tenho uma cadela de sete anos, castrada e sociavel.' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET cidade = 'Maricá' WHERE cidade = 'Marica' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET mensagem = 'Sítio com dois hectares cercados. Já adotei três cães daqui nos últimos anos.' WHERE mensagem = 'Sitio com dois hectares cercados. Ja adotei tres caes daqui nos ultimos anos.' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET cidade = 'Itaboraí' WHERE cidade = 'Itaborai' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET mensagem = 'Tenho dois gatos castrados. Quero um terceiro que se dê bem com eles.' WHERE mensagem = 'Tenho dois gatos castrados. Quero um terceiro que se de bem com eles.' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE candidatura SET mensagem = 'Apartamento grande, trabalho híbrido, disponível para acompanhamento.' WHERE mensagem = 'Apartamento grande, trabalho hibrido, disponivel para acompanhamento.' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE evento_do_animal SET descricao = 'Antirrábica' WHERE descricao = 'Antirrabica' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE evento_do_animal SET descricao = 'Vermifugação de rotina' WHERE descricao = 'Vermifugacao de rotina' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE evento_do_animal SET descricao = 'Consulta veterinária de rotina' WHERE descricao = 'Consulta veterinaria de rotina' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE evento_do_animal SET descricao = 'Castração realizada no mutirão' WHERE descricao = 'Castracao realizada no mutirao' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));
UPDATE abrigo SET nome = 'Abrigo São Francisco' WHERE nome = 'Abrigo Sao Francisco' AND id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE abrigo SET cidade = 'Niterói' WHERE cidade = 'Niteroi' AND id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app');
UPDATE candidatura SET motivo_da_recusa = 'A casa ainda não tem cerca, e este animal pula muro.' WHERE motivo_da_recusa = 'A casa ainda nao tem cerca, e este animal pula muro.' AND animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app'));

-- nome e cidade de quem adotou tambem aparecem dentro da descricao do evento
UPDATE evento_do_animal SET descricao = replace(descricao, 'Niteroi', 'Niterói') WHERE animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app')) AND position('Niteroi' in descricao) > 0;
UPDATE evento_do_animal SET descricao = replace(descricao, 'Joao Lima', 'João Lima') WHERE animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app')) AND position('Joao Lima' in descricao) > 0;
UPDATE evento_do_animal SET descricao = replace(descricao, 'Sao Goncalo', 'São Gonçalo') WHERE animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app')) AND position('Sao Goncalo' in descricao) > 0;
UPDATE evento_do_animal SET descricao = replace(descricao, 'Marica', 'Maricá') WHERE animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app')) AND position('Marica' in descricao) > 0;
UPDATE evento_do_animal SET descricao = replace(descricao, 'Itaborai', 'Itaboraí') WHERE animal_id IN (SELECT id FROM animal WHERE abrigo_id = (SELECT id FROM abrigo WHERE email = 'abrigo@guarida.app')) AND position('Itaborai' in descricao) > 0;
COMMIT;
