-- Abrigo, ONG ou protetor independente que mantem os cadastros.
CREATE TABLE abrigo (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(120) NOT NULL,
    email      VARCHAR(160) NOT NULL,
    senha_hash VARCHAR(72)  NOT NULL,
    cidade     VARCHAR(80)  NOT NULL,
    telefone   VARCHAR(20),
    criado_em  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_abrigo_email UNIQUE (email)
);

CREATE TABLE animal (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abrigo_id                   BIGINT       NOT NULL,
    nome                        VARCHAR(60)  NOT NULL,
    especie                     VARCHAR(20)  NOT NULL,
    raca                        VARCHAR(60),
    sexo                        VARCHAR(10)  NOT NULL,
    porte                       VARCHAR(10)  NOT NULL,
    nascimento_estimado         DATE         NOT NULL,
    peso_em_gramas              INTEGER      NOT NULL,
    castrado                    BOOLEAN      NOT NULL DEFAULT FALSE,
    vacinado                    BOOLEAN      NOT NULL DEFAULT FALSE,
    vermifugado                 BOOLEAN      NOT NULL DEFAULT FALSE,
    historia                    VARCHAR(1000),
    observacoes_de_saude        VARCHAR(500),
    status                      VARCHAR(20)  NOT NULL,
    data_de_entrada             DATE         NOT NULL,
    criado_em                   TIMESTAMP(6) NOT NULL,
    atualizado_em               TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_animal_abrigo FOREIGN KEY (abrigo_id) REFERENCES abrigo (id)
);

-- O catalogo publico filtra quase sempre por estas colunas juntas.
CREATE INDEX ix_animal_status_especie ON animal (status, especie);
CREATE INDEX ix_animal_abrigo ON animal (abrigo_id, criado_em);

-- Um animal tem varios tracos, e a busca por traco precisa ser indexada.
CREATE TABLE temperamento_do_animal (
    animal_id    BIGINT      NOT NULL,
    temperamento VARCHAR(30) NOT NULL,
    CONSTRAINT pk_temperamento PRIMARY KEY (animal_id, temperamento),
    CONSTRAINT fk_temperamento_animal FOREIGN KEY (animal_id) REFERENCES animal (id) ON DELETE CASCADE
);

-- Linha do tempo: tudo o que aconteceu com o animal desde a entrada.
CREATE TABLE evento_do_animal (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id  BIGINT       NOT NULL,
    tipo       VARCHAR(20)  NOT NULL,
    descricao  VARCHAR(300) NOT NULL,
    acontecido DATE         NOT NULL,
    criado_em  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_evento_animal FOREIGN KEY (animal_id) REFERENCES animal (id) ON DELETE CASCADE
);

CREATE INDEX ix_evento_animal ON evento_do_animal (animal_id, acontecido);

-- Candidatura de quem quer adotar. Chega pelo catalogo publico, sem cadastro.
CREATE TABLE candidatura (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id           BIGINT       NOT NULL,
    nome                VARCHAR(120) NOT NULL,
    email               VARCHAR(160) NOT NULL,
    telefone            VARCHAR(20)  NOT NULL,
    cidade              VARCHAR(80)  NOT NULL,
    moradia             VARCHAR(20)  NOT NULL,
    area_protegida      BOOLEAN      NOT NULL,
    tem_outros_animais  BOOLEAN      NOT NULL,
    mensagem            VARCHAR(800),
    status              VARCHAR(20)  NOT NULL,
    motivo_da_recusa    VARCHAR(300),
    criada_em           TIMESTAMP(6) NOT NULL,
    atualizada_em       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_candidatura_animal FOREIGN KEY (animal_id) REFERENCES animal (id) ON DELETE CASCADE
);

CREATE INDEX ix_candidatura_animal ON candidatura (animal_id, criada_em);
CREATE INDEX ix_candidatura_status ON candidatura (status, criada_em);
